version: '3'

services:
  sensor_integration:
    build:
      context: .
      dockerfile: sensor_integration/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  data_processing:
    build:
      context: .
      dockerfile: data_processing/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db

  web_app_backend:
    build:
      context: .
      dockerfile: web_app_backend/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - db

  sensor-dashboard:
    build:
      context: .
      dockerfile: sensor-dashboard/Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sensor_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

